/** Paths (under /public) for static images used by more than one component. */
export const assets = {
  heroImage: "/images/cover-image-2.png",
  sellHeaderImage: "/images/header-images/contemporary-homes.png",
  appleWalletBadge: "/images/US-UK_Add_to_Apple_Wallet_RGB_101421.svg",
  cardQr: "/images/card/daniel-cantero-card-qr.png",
  glyphs: {
    sell: "/images/glyphs/find-homes-south-jersey-2.svg",
    buy: "/images/glyphs/for-sale-south-jersey.svg",
  },
  favicon: {
    appleTouch: "/images/favicon/apple-touch-icon.png",
    png32: "/images/favicon/favicon-32x32.png",
    png16: "/images/favicon/favicon-16x16.png",
  },
} as const;

/** Served by an explicit Express route in server.js. */
export const WALLET_PASS_PATH = "/dcantero-card.pkpass";
/** Generated by server/app.ts from the site config. */
export const VCARD_PATH = "/contact.vcf";
